### ISSUE TITLE
Questions about fit_maple

### ISSUE THREAD

**Issue by zqsha** [carter-allen/maple#1]
Hi, thanks for developing such an amazing toolbox. So far, I successfully run the example (https://carter-allen.github.io/stxBrain_all_maple.html ). But, I have a question about the option of 'fit_maple' function. In the example, we can see it used 'brain_fit_PCs_K10 <- fit_maple(brain,K = 10,emb = "PCs",covars = "region")' to model the clusters. What does the 'covars' refer to? If I run this function using my own samples, do I also need to specify this option?
Another question is that if my data has a batch effect, after running RunPCA, is it necessary to harmony the data first and then run the fit_maple? Based on the example above, it does not have harmony the data.

Thanks,
Cain

**Comment by carter-allen** [comment]
Hi Cain, thanks for your interest! Just FYI, the package is still under development as we are preparing the package for submission to CRAN and are also preparing a manuscript for the underlying methodology. 

To answer your question though, "covars" refers to a vector of meta data variables you would like to use to explain cell spot sub-population membership. So for the mouse brain example, using covars = "region" corresponds to using an indicator variable that encodes whether each cell spot was in the anterior or posterior brain region. The idea is that you can use biologically relevant variables like this to explain differential abundance of these sub-populations (clusters) in your data. The names of "covars" will vary based on your data and should correspond to column names of the meta data in the Seurat object. You can also leave this argument blank if you have no such variables in mind.

Please let me know if you have any other questions or feedback as we continue to make the package more user friendly. 

Best,
Carter

**Comment by zqsha** [comment]
Hi Carter,
Thanks for your reply. When I run my samples by adopting the codes from the example, only one step met an error, that is when I run 'brain_fit_PCs_K7 <- fit_maple(maple_seurat,K = 7,emb = "PCs")', it shows
Error in seurat_obj@images[[l]] : subscript out of bounds
I try to run the clustering analysis with around 10 samples.
For previous steps, they are all correct without bugs. Any thoughts on fixing it?

Here is the data that I have
![Capture](https://user-images.githubusercontent.com/27337033/149098230-7eb919ef-f446-4b88-a7ec-e8a7c07af304.PNG)

Thanks,
Cain

**Comment by zqsha** [comment]
OH, Got it. Because it missed the images information, in other words, it's empty in the maple_seurat@images. Previously, I used SingleCellExperiment to run the analysis, but now it's seurat structure. So, I used the following command line to covert SCE to SEURAT, but missed image data.
maple.seurat1 <- as.Seurat(sce1, counts = "counts", data = "logcounts")
My image data is already in the sce@metadata. But, I have no idea about converting the sce@metadata to the maple.seurat@images.
PS. I think it would be great if this maple toolbox add one option to convert the SCE structure to SEURAT structure, as some users are using SCE to analyze the data.

Best,
Cain

**Comment by zqsha** [comment]
Hi Carter, I still did not fix the problem. I am sorry that I am not familiar with seurat structure. I do not know how to convert the sce@metadata into the maple.seurat@images. My image data is now in the sce@metadata. Do you have any suggestions about this conversion? Thank you so much. I really appreciate this.

**Comment by carter-allen** [comment]
I see, apologies for misunderstanding. Usually when starting from an merged multi-sample Seurat object there should be a slot seurat_object@images, while is a list of length L, where L is the number of samples you have integrated. Each entry of the list seurat_object@images[[l]] (for l = 1,...,L) should contain a matrix called coordinates with columns "row" and "col" giving the 2-d spatial coordinates of that sample. In short, you should have seurat_obj@images[[l]]@coordinates$col and seurat_obj@images[[l]]@coordinates$row populated with numeric coordinates for l = 1,...,L. Can you check to see if that's the case?

**Comment by zqsha** [comment]
Hi Carter,
Thanks for your reply. If I only use maple.seurat1 <- as.Seurat(sce1, counts = "counts", data = "logcounts"), then maple.seurat1@images is just an empty list. 
Next, I used 'Read10X_Image' function to reload the image information. 
maple.seurat1@images = list(
  v10j27_028_a1 = Read10X_Image(
    image.dir = paste0(image_folder,'ANW945_GFI1_V10J27-028_A1/outs/spatial'),
    image.name = "tissue_lowres_image.png",
    filter.matrix = TRUE
  )
)
Then, I saw the maple.seurat1@images (below). The top is the first sample (i.e. maple.seurat1), while the bottom is the second sample (i.e. maple.seurat2)

The first sample
![Capture1](https://user-images.githubusercontent.com/27337033/149210502-0662ced0-c0eb-4463-b959-4be214b4fd30.PNG)

The second sample
![Capture2](https://user-images.githubusercontent.com/27337033/149210530-c9f8d0e0-02d2-4956-b93d-578a41a18b5f.PNG)

But, when I merge both sample by ''merge" function in the SEURAT toolbox.
maple_seurat <- merge(maple.seurat1,maple.seurat2)

It shows the following error:
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed

Interestingly, if I do not load image information into seurat data, then I can merge the data. I really do not know why it happens. Do you have any suggestions?

Thanks,
Cain

**Comment by carter-allen** [comment]
I see, so the error occurs with the Seurat merge() function. It seems others have encountered something similar: https://github.com/satijalab/seurat/issues/1710.

Could you check the row names of images@coordinates for each object and make sure there are no shared row names between the two?

**Comment by zqsha** [comment]
I checked the row names of images@coordinates for each object. The row names of images@coordinates are the barcode (below), and some of them are overlapping, as the barcode represents the spatial information in each capture area, so they should be shared in different samples.
The first sample:
![Capture1](https://user-images.githubusercontent.com/27337033/149286264-f9a1cb77-2cd3-4ae5-abdc-27b3ab93a4c3.PNG)

The second sample:
![Capture2](https://user-images.githubusercontent.com/27337033/149286320-a94a51a5-399b-498c-986c-b68aca4330cb.PNG)

I also take a look at the positive control in your sample, i.e. brain1 and brain2. We can see they are indeed overlapping.
Here are the images@coordinates in brain1.
![Capture1](https://user-images.githubusercontent.com/27337033/149287309-94f48620-d60a-401c-affc-2c995b1deb64.PNG)

Here are the images@coordiantes in brain2.
![Capture2](https://user-images.githubusercontent.com/27337033/149287334-c282b59f-7875-46ff-b233-611dabac97c8.PNG)

Thanks,
Cain

**Comment by carter-allen** [comment]
Hi Cain, if you feel comfortable, could you please send your two samples saved as seurat_object .RData files to my email (carter.allen12@gmail.com) so I can inspect the issue? You might also want to reach out to the Seurat developers for more information since it is an issue with the Seurat merge function. 

Best,
Carter

**Comment by zqsha** [comment]
Hi Carter, OK. Thank you so much for your help, I really appreciate this. I agree. As this is the seurat issue, I am sorry to trouble you to fix the issue from another toolbox. Let me first talk to the Seurat developers to fix it. If I meet any issue with maple, I will let you know. Thanks again for all of your help. I think this is the greatest toolbox for clustering analysis on spatial data. :-)
Thanks,
Cain

**Comment by carter-allen** [comment]
Sure, sounds good, I appreciate your patience and understanding! We'll continue work towards making the workflow as easy as possible and I will look more into supporting SingleCellExperiment objects.

**Comment by zqsha** [comment]
That would be great to integrate SCE objects. When I run the example (https://carter-allen.github.io/stxBrain_all_maple.html )
VariableFeatures(brain) <- c(VariableFeatures(brain1),
                             VariableFeatures(brain2),
                             VariableFeatures(brain3),
                             VariableFeatures(brain4))
brain <- RunPCA(brain)

Question1: I guess it uses the top 3000 HVG genes to run the PCA. Right? Do you think the number of HVG genes can affect the clustering results? In other words, do we need to try the top 1000 HVGs or top 2000 HVGs to run the analysis?

Question2 Given that lots of toolboxes have this 'RunPCA' function, I guess this will generate the top 50 PCs, which will be used to run the following clustering analysis. Right?

Question3: Given that maple is run the cross-sample clustering analysis, different samples might have different library sizes. Do we need to first normalize the library size? For example, I converted the normalized data in SCE to seurat objects using maple.seurat2 <- as.Seurat(sce2, counts = "counts", data = "logcounts"). But, as the example does, it also used SCTransform to normalize the data. So, I guess that's fine?

Question4: How many samples do the maple handle? If I have 50 samples, does maple work with these samples?

Thanks,
Cain

**Comment by carter-allen** [comment]
Hi Cain, they are good questions and are topics we deal with in detail in the upcoming manuscript! To answer them briefly: 

1) By default Seurat uses the top 2000 HVGs ([see the introductory vignette](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html)). As to how this affects results, it will of course depend on the data set, but it is very unlikely that increasing the HVGs past 2,000 would have substantial effects of the final results. You can always try it an see, but each additional HVG should in some sense contain less information than the last. 

2) Correct. By default, Seurat stores the first 50 PCs. However (details contained in our upcoming paper), MAPLE is able to identify tissue architecture accurately using far fewer than 50 PCs. This is why I have set the default to 8 dimensions, but you can adjust this with the "n_dim" parameter in fit_maple(). Note that there are more sophisticated dimension reduction methods like SpaGCN and scGNN that capture tissue architecture much more efficiently (i.e., with fewer dimensions) relative to PCA. All tissue architecture identification methods including MAPLE are sensitive to the features used as input. So, while PCA is the default, often performance can be improved by using "spatially aware" dimension reduction approached like SpaGCN or scGNN. 

3) SCTransform is currently the only normalization step necessary. However, we are still finalizing the package for submission to CRAN so the workflow is subject to change possibly.

4) It depends on the hardware available and the amount of time you are willing to wait. On a M1 iMac with 8GB RAM, MAPLE takes approximately 10 mins/1,000 iterations for an integrated data set with ~5,000 cell spots. By default, MAPLE runs for 2,000 total iterations, which we have found to be sufficient for convergence in all applied setting. You can change the number of iterations using the nsim parameter. 

Please note that since MAPLE is a Bayesian method that relies on MCMC sampling, it is inherently computationally demanding. We have implemented computationally demanding steps in C++ using Rcpp, but reducing computation time is an ongoing effort. We have found the tradeoff to be well worth it given the benefits of Bayesian modeling, such as uncertainty quantification for cell spot labels. Again, a more detailed discussion will be included in a forthcoming manuscript. 

Best,
Carter

**Comment by carter-allen** [comment]
Ok, since the original problem is resolved I will close this issue for the sake of organization. Feel free to open other issues for specific problems. Regarding your questions

1) Please consult the Seurat documentation for more details on their pre-processing functions. 

3) Yes, maple is compatible with Harmony as well. Just make sure to provide the Harmonized feature matrix separately to fit_maple() via the "emb" argument.

4) It depends on the data. You can check for convergence of cell spot labels by looking at maple_object$Z[,i], where i is a cell spot of interest. Same applies to other model parameters like maple_object$MU. It will make more sense once the paper comes out.

5) [It is known to occur sometimes with RccppArmadillo](https://stackoverflow.com/questions/55963059/matrix-not-symmetric-warning-in-armadillo-is-too-strict). Likely it is because of mixture components (cell spot clusters) containing very few cell spots at some point throughout the MCMC sampler. Usually the MCMC will figure this out and resolve to a better solution and the warning will go away. You could also try to reduce the number of mixture components (K). Regarding R studio "flashing back" I'm sorry, but I'm not sure what you mean by that.
